apiVersion: apps/v1
kind: Deployment
metadata:
  name: cb-admin-api
spec:
  selector:
    matchLabels:
      app: cb-admin-api
  template:
    metadata:
      labels:
        app: cb-admin-api
    spec:
      terminationGracePeriodSeconds: 120
      imagePullSecrets:
        - name: registrypullsecret
      containers:
      - name: cb-admin-api
        image: harbor.baokim.vn/cb/cb-admin-api:v1.0.0
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: 256Mi
            cpu: 200m
          limits:
            memory: "1Gi"
        ports:
        - name: http
          containerPort: 80
        envFrom:
        - configMapRef:
            name: env-cb-admin-api
        lifecycle:
          preStop:
            exec:
              command:
              - /bin/bash
              - -c
              - |
                echo "PreStop duoc kich hoat. Dang tam dung 60 giay de cho giao dich..."
                sleep 60
        volumeMounts:
          - mountPath: /var/www/html/storage/logs
            name: cb-admin-api-logs
      volumes:
        - name: cb-admin-api-logs
          persistentVolumeClaim:
            claimName: cb-logs
