apiVersion: apps/v1
kind: Deployment
metadata:
  name: b2b-core
spec:
  selector:
    matchLabels:
      app: b2b-core
  template:
    metadata:
      labels:
        app: b2b-core
    spec:
      terminationGracePeriodSeconds: 120
      imagePullSecrets:
        - name: registrypullsecret
      containers:
      - name: b2b-core
        image: harbor.baokim.vn/b2b/b2b-core:latest
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: 256Mi
            cpu: 200m
          limits:
            memory: "1Gi"
        ports:
        - name: http
          containerPort: 80
        envFrom:
        - configMapRef:
            name: env-b2b-core
        lifecycle:
          preStop:
            exec:
              command:
              - /bin/bash
              - -c
              - |
                echo "PreStop duoc kich hoat. Dang tam dung 60 giay de cho giao dich..."
                sleep 60


